package dev.uten2c.syringe.api.hud;

public enum HudPart {
    SPYGLASS_OVERLAY,
    PUMPKIN_OVERLAY,
    POWDER_SNOW_OUTLINE_OVERLAY,
    PORTAL_OVERLAY,
    HOTBAR,
    CROSSHAIR,
    BOSS_BAR,
    ARMOR_BAR,
    HEALTH_BAR,
    HUNGER_BAR,
    AIR_BAR,
    MOUNT_HEALTH_BAR,
    MOUNT_JUMP_BAR,
    EXPERIENCE_BAR,
    HELD_ITEM_TOOLTIP,
    STATUS_EFFECT_OVERLAY,
    SCOREBOARD_SIDEBAR,
    PLAYER_LIST_HUD,
}
